### get posts

GET http://localhost:3000/api/posts
Content-Type: application/json

### post posts

POST http://localhost:3000/api/posts
Content-Type: application/json

{
  "title": "1st Post",
  "description": "Description of 1st post"
}

### get single post

GET http://localhost:3000/api/posts/9c9468f9-eb6e-46b9-b08c-7cd31f98dc7d
Content-Type: application/json

### patch post

PATCH http://localhost:3000/api/posts/3b42c282-b5cb-4a70-921d-46b9ebaef422
Content-Type: application/json

{
  "title": "Title of 1st post",
  "description": "---------"
}

### delete post

DELETE http://localhost:3000/api/posts/3b42c282-b5cb-4a70-921d-46b9ebaef422
Content-Type: application/json