### get posts

GET http://localhost:3000/api/posts
Content-Type: application/json

### post posts

POST http://localhost:3000/api/posts
Content-Type: application/json

{
  "title": "1st Post",
  "description": "Description of 1st post"
}

### get single post

GET http://localhost:3000/api/posts/be7bedd0-ded2-4b08-b768-eddc538a495b
Content-Type: application/json

### patch post

PATCH http://localhost:3000/api/posts/be7bedd0-ded2-4b08-b768-eddc538a495b
Content-Type: application/json

{
  "title": "Title of 1st post",
  "description": "---------"
}

### delete post

DELETE http://localhost:3000/api/posts/be7bedd0-ded2-4b08-b768-eddc538a495b
Content-Type: application/json